### ISSUE TITLE
HMR breaks instanceof operator

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#547]

**Comment by rllola** [comment]
I am able to reproduce the issue 
![screenshot from 2017-12-07 04-38-26](https://user-images.githubusercontent.com/1772945/33697721-ac6f36cc-db08-11e7-867f-fa35a4811304.png)

**Comment by rllola** [comment]
The only error that I is linked to instanceOf is a warning. Otherwise it works fine for me.
![screenshot from 2017-12-07 04-38-26](https://user-images.githubusercontent.com/1772945/33697780-f81b0a9c-db08-11e7-97c2-913328443660.png)

**Comment by bedeho** [comment]
Yes, but that means the native `instanceof` operator is no longer working, which has wider implications. A minimal example would be great to both isolate whether we are doing somethign wrong with our HMR setup, or whether there is something fundamentally wrong with HMR, which we can ask them about.

**Comment by rllola** [comment]
The issue seems to resolved with the latest version of react-hot-reloading : https://github.com/gaearon/react-hot-loader/issues/720

We have updated to use this version in this PR : https://github.com/JoyStream/joystream-desktop/pull/613
