### ISSUE TITLE
Introduce user settings

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#550]
Introductory features
- Change download folder (highly requested)

Long term we can have other things like
- Whether or not to automatically do paid uploads?
- Default term controls
- Change language
- Change local currency
- Alter price feed

**Comment by bedeho** [comment]
Almost started doing this in #546 , since I need a bunch of defaults, but just hard coded for now. 

This seems like a good approach:

- Add a new subfolder under /core called `ApplicationSettingsDb`, and move the `core/ApplicationSettings.js`into this folder, and rename
- Add hooks to this class so that one can subscribe to when the databse is updated
- Create `ApplicationSettingsDbStore`to be a MOBX store in the same folder. The store is needed to keep various UI parts in synch
- Add static `.fromStore` constructor on this class, which initializes the store, and hooks up to observables.
- Pass in this store to the `UiStore` ?

Question: Who creates ApplicationSettingsDbStore  object? probably whomever is currently creation `ApplicationStore`

**Comment by rllola** [comment]
#602 introduce `applicationSettings` which will save the default download folder in a config file. Only this settings has been added but it make it easy to add other in the future. Also `applicationSettings` is more link to the application in general than the UI so it is created by the `applicationStore`.
