### ISSUE TITLE
TorrentStore isTerminating is out of synch with state machine

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#713]
It used to have composite state `Terminating`, and as such the `TorrentStore` had implementation

```
    @computed get
    isTerminating() {
        return this.state.startsWith('Terminating')
    }
```

however this state is now gone, we just have top level states `StoppingExtension` and `GeneratingResumeData`, and possibly more. Revisit to confirm.

**Comment by mnaamani** [comment]
fixed in https://github.com/JoyStream/joystream-desktop/pull/723
