### ISSUE TITLE
example torrents not always appearing in downloading scene when onboarding

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#730]

**Comment by mnaamani** [comment]
I've tested again several times with the now active status bar. Torrent are definitely not being added sometimes. It's not about taking a long time to check/load.

**Comment by mnaamani** [comment]
Here is the problem. The problem happens when we are attempting to adding the example torrents using the `Application.addTorrent` method which only always torrents to be added when the application state is STARTED. 

So if you click on "Let's go" too soon. the torrents do not get added :)

**Comment by mnaamani** [comment]
Quick Fix https://github.com/JoyStream/joystream-desktop/pull/745
I'm not sure if there are any bad side effects of adding torrents before application state is STARTED?
Thats how we load torrents from the database..
