### ISSUE TITLE
when closing app from community scene, during onboarding the community icons are still visible.

### ISSUE THREAD

**Issue by mnaamani** [JoyStream/joystream-desktop#741]
![screen shot 2018-02-26 at 4 55 03 pm](https://user-images.githubusercontent.com/1621012/36677091-fe641f90-1b15-11e8-9733-b712ecc962fb.png)

**Comment by mnaamani** [comment]
clicking on the close button triggers the slack community link to open instead.

**Comment by bedeho** [comment]
Done in https://github.com/JoyStream/joystream-desktop/pull/750
