### ISSUE TITLE
Wallet new incoming payments appear at the bottom of the payment list

### ISSUE THREAD

**Issue by mnaamani** [JoyStream/joystream-desktop#767]
<img width="927" alt="screen shot 2018-02-28 at 5 09 57 pm" src="https://user-images.githubusercontent.com/1621012/36794922-561c8b6a-1caa-11e8-96f1-63385cd1c812.png">

**Comment by mnaamani** [comment]
This is likely because there is no timestamp/date ?

**Comment by bedeho** [comment]
Done in https://github.com/JoyStream/joystream-desktop/pull/801
