### ISSUE TITLE
incorrect use of client.peers Map in torrent statemachine

### ISSUE THREAD

**Issue by mnaamani** [JoyStream/joystream-desktop#774]
<img width="1142" alt="screen shot 2018-03-02 at 10 12 27" src="https://user-images.githubusercontent.com/1621012/36892040-3ac536ce-1e0c-11e8-9dea-3a13af5aeb47.png">

**Comment by mnaamani** [comment]
I also saw this on our seeding server. Error seems to be in this input handler on the torrent state machine:
```
            uploadStarted: function (client, alert) {
              var peer = client.peers[alert.pid]
              peer.uploadStarted(alert)
            },
```
for some reason peer is `undefined`

**Comment by bedeho** [comment]
This seems clearly broken, as `peers` is now a `Map`, but before it was just a plain javascript dictionary, which is what we are seeing there.

**Comment by bedeho** [comment]
Done in  https://github.com/JoyStream/joystream-desktop/pull/784
