### ISSUE TITLE
Broken assert import in start paid downloading component

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#808]
Breaks in production! is in `getText` of `StartPaidDownloading.js`, where asserts are made, not sure why this was not spotted prior. Is severe bug.

**Comment by mnaamani** [comment]
Did you have the media player open ?
If so and the wallet was not ready .. this would explain it. We are not handling that case in `getText`
This should fix it: #809

**Comment by mnaamani** [comment]
done in #809
