### ISSUE TITLE
Torrent removal bug

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#862]
When removing a torrent on a scene with multiple torrents, it often is the case that a new torrent row moves under the cursor, however, the toolbar is still not displayed. This is of particular annoyance when you want to remove many torrents in a row.

**Comment by mnaamani** [comment]
Tried to simply use `onMouseOver` event to show the toolbar, but it doesn't work when an element comes under the mouse. You must actually move the mouse slightly.

**Comment by bedeho** [comment]
done in #878
