### ISSUE TITLE
Misplaced tooltips

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#893]
They seem to not render properly, in particular in the toolbar

https://files.slack.com/files-pri/T06BJURQU-F9S6E7NSD/image.png

**Comment by donaloconnor** [comment]
Seeing this also here:
![image](https://user-images.githubusercontent.com/6394033/37719191-59b88616-2d1c-11e8-9a97-38548107dfee.png)

I can reproduce it by hovering over the BCH balance first (Renders correctly) then move mouse to right over the transfer speed (renders correctly) then back to BCH balance and it renders incorrectly. It renders correctly again if you move mouse off the BCH balance to the left side of it. 
Happens in the Downloads/Uploads tab. Does not happen on the Finished tab.

**Comment by bedeho** [comment]
Hey, thanks for his. We have had issues with the tooltips, will look into this for the next release (1.0.2), I suspect why this is happening.

**Comment by bedeho** [comment]
Done in  https://github.com/JoyStream/joystream-desktop/pull/927
