### ISSUE TITLE
Change default port from 6881

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#914]
## Background

Based on feedback from user dynamic_unreality@reddit

<img width="887" alt="screen shot 2018-03-23 at 00 58 06" src="https://user-images.githubusercontent.com/437292/37817873-7d81e9b0-2e35-11e8-82b3-84cc2e053cfc.png">

## Solution

Will require migration

**Comment by mnaamani** [comment]
I'm reviewing this and looking at:
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
Perhaps we can pick an unregistered port.

**Comment by mnaamani** [comment]
Making sure not to pick a port number in the [ephemeral port range](http://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html) used by the OS.

To satisfy all the platforms we are supporting, a value in the range 5000 - 32768 is acceptable that isn't a well known port for some other service that would be likely to be on the same machine running a joystream client.

**Comment by mnaamani** [comment]
Decided on `7881` It is similar to the default port libtorrent listens on, and appears to be unassigned in IANA registry.

**Comment by bedeho** [comment]
Done in #921
